name: Trunk Code Quality setup
description: Set up dependencies for Trunk Code Quality
runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@v4 # zizmor: ignore[unpinned-uses]
          with:
              version: 10

        - name: Install Root NodeJS dependencies
          shell: bash
          run: |
              pnpm install --frozen-lockfile

        - name: Install WWW NodeJS dependencies
          shell: bash
          run: |
              cd www
              pnpm install --frozen-lockfile
